-- Execute no SQL Editor do Supabase

create table if not exists public.music_news (
  id bigint generated by default as identity primary key,
  source_url text not null unique,
  source_name text not null,
  title text not null,
  summary text null,
  image_url text null,
  published_at timestamptz null,
  tags text null,
  score integer null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_music_news_published_at on public.music_news (published_at desc);

create table if not exists public.collector_heartbeat (
  key text primary key,
  last_seen_at timestamptz not null default now(),
  status text not null default 'ok',
  meta_json jsonb null
);
