-- RLS seguro para o feed de noticias e heartbeat do coletor
-- Modelo:
-- - `music_news`: leitura somente para authenticated, escrita apenas via backend com service_role.
-- - `collector_heartbeat`: sem acesso para anon/authenticated; apenas backend com service_role.
-- Observacao: `service_role` do Supabase ignora RLS. Ele deve existir apenas no backend.

begin;

create table if not exists public.music_news (
  id bigint generated by default as identity primary key,
  source_url text not null unique,
  source_name text not null,
  title text not null,
  summary text null,
  image_url text null,
  published_at timestamptz null,
  tags text null,
  score integer null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_music_news_published_at on public.music_news (published_at desc);

create table if not exists public.collector_heartbeat (
  key text primary key,
  last_seen_at timestamptz not null default now(),
  status text not null default 'ok',
  meta_json jsonb null
);

alter table public.music_news enable row level security;
alter table public.collector_heartbeat enable row level security;
alter table public.music_news force row level security;
alter table public.collector_heartbeat force row level security;

revoke all on table public.music_news from anon, authenticated;
revoke all on table public.collector_heartbeat from anon, authenticated;

grant select on table public.music_news to authenticated;

drop policy if exists music_news_read_authenticated on public.music_news;
create policy music_news_read_authenticated
on public.music_news
for select
to authenticated
using (auth.uid() is not null);

-- Nenhuma policy em collector_heartbeat por design.
-- Somente service_role do backend deve ler ou escrever nessa tabela.

commit;
